name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: Eric-Du-BH/kernel_build_action@main
        with:
          kernel-url: https://github.com/PixelExperience-Devices/kernel_oneplus_msm8998
          kernel-branch: eleven
          config: lineage_oneplus5_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 11
          aosp-clang-version: r365631c
